#!/usr/bin/env bash
#
# fetch-secrets.sh — pull secrets from Google Secret Manager into LOCAL,
# git-ignored files so the project can build/run. Nothing here is ever committed.
#
#   backend/.env                         <- APP_TOKEN  (local backend dev)
#   ClearMaxxApp/.../Services/Secrets.swift  <- CMSecrets.appToken      (iOS build)
#
# The backend runs on VERTEX AI (no Gemini API key), so only the app token is
# fetched. Requires: authenticated gcloud with access to project faraz-mobile-apps.
#
set -euo pipefail
PROJECT="faraz-mobile-apps"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS_SWIFT="$ROOT/ClearMaxxApp/ClearMaxx/Services/Secrets.swift"
BACKEND_ENV="$ROOT/backend/.env"

get() { gcloud secrets versions access latest --secret="$1" --project "$PROJECT" 2>/dev/null; }

echo "▶︎ Fetching secrets from Secret Manager ($PROJECT)…"
APP_TOKEN="$(get clearmaxx-app-token)"

if [ -z "${APP_TOKEN:-}" ]; then
  echo "✗ Could not read clearmaxx-app-token. Is gcloud authed with access to $PROJECT?" >&2
  exit 1
fi

# iOS (git-ignored)
cat > "$SECRETS_SWIFT" <<EOF
//
//  Secrets.swift  — GIT-IGNORED. Generated by ./fetch-secrets.sh. Do NOT commit.
//
enum CMSecrets {
    static let appToken = "${APP_TOKEN}"
}
EOF
echo "  ✓ wrote $SECRETS_SWIFT"

# backend local dev (git-ignored)
cat > "$BACKEND_ENV" <<EOF
# Local dev only (git-ignored). Production reads the token from Secret Manager;
# Vertex AI auth comes from ADC (gcloud auth application-default login).
APP_TOKEN=${APP_TOKEN}
VERTEX_LOCATION=us-central1
PORT=8080
EOF
echo "  ✓ wrote $BACKEND_ENV"
echo "✓ Done. These files are git-ignored and never pushed."
