//
//  SkinAnalysisService.swift
//  ClearMaxx — calls the deployed backend to analyze a face photo with Gemini.
//

import UIKit

enum CMConfig {
    /// Deployed App Engine service — Vertex AI backend on project faraz-mobile-apps.
    static let backendURL = URL(string: "https://clearmaxx-dot-faraz-mobile-apps.uc.r.appspot.com")!

    /// Shared app token — matches Secret Manager `clearmaxx-app-token`.
    /// Loaded from the git-ignored `Secrets.swift` (generated by ./fetch-secrets.sh),
    /// so no token value is ever committed to the repo.
    static var appToken: String { CMSecrets.appToken }
}

// MARK: - API response models (must match backend JSON exactly)

struct SkinAnalysis: Codable {
    let clearScore: Int
    let confidence: Int
    let skinType: String
    let summary: String
    let metrics: [APIMetric]
    let routineSuggestions: [String]
}

struct APIMetric: Codable {
    let name: String
    let value: Int
    let severity: String
    let summary: String
    let ingredients: [String]
    let tips: [String]
}

private struct AnalyzeResponse: Codable {
    let success: Bool?
    let result: SkinAnalysis?
    let error: String?
}

/// User-facing scan errors. Every case maps to a calm, plain-language message —
/// we never surface raw status codes or server strings like "Unauthorized" to
/// the user. The underlying detail is printed to the console for developers.
enum SkinAnalysisError: LocalizedError {
    case encodingFailed
    case offline
    case timedOut
    case badImage
    case unauthorized
    case rateLimited
    case serverBusy
    case unknown

    var errorDescription: String? {
        switch self {
        case .encodingFailed: return "We couldn't prepare that photo. Please try another one."
        case .offline:        return "You appear to be offline. Check your connection and try again."
        case .timedOut:       return "Your scan is taking longer than usual. Please try again."
        case .badImage:       return "We couldn't read your face clearly. Try a well-lit photo facing the camera."
        case .unauthorized:   return "We couldn't start your scan right now. Please update ClearMaxx or try again later."
        case .rateLimited:    return "A lot of glow-ups are happening right now. Please try again in a moment."
        case .serverBusy:     return "Our skin analysis is taking a quick break. Please try again shortly."
        case .unknown:        return "Something went wrong during your scan. Please try again."
        }
    }
}

// MARK: - Service

enum SkinAnalysisService {
    static func analyze(image: UIImage) async throws -> SkinAnalysis {
        guard let jpeg = image.cm_resized(maxDimension: 1024).jpegData(compressionQuality: 0.7) else {
            throw SkinAnalysisError.encodingFailed
        }

        var req = URLRequest(url: CMConfig.backendURL.appendingPathComponent("api/skin/analyze"))
        req.httpMethod = "POST"
        req.timeoutInterval = 60
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.setValue(CMConfig.appToken, forHTTPHeaderField: "X-App-Token")
        req.httpBody = try JSONSerialization.data(withJSONObject: ["image_base64": jpeg.base64EncodedString()])

        let data: Data
        let resp: URLResponse
        do {
            (data, resp) = try await URLSession.shared.data(for: req)
        } catch let e as URLError {
            switch e.code {
            case .notConnectedToInternet, .networkConnectionLost, .dataNotAllowed:
                throw SkinAnalysisError.offline
            case .timedOut:
                throw SkinAnalysisError.timedOut
            default:
                print("[SkinAnalysis] network error: \(e.code.rawValue) \(e.localizedDescription)")
                throw SkinAnalysisError.unknown
            }
        }

        let status = (resp as? HTTPURLResponse)?.statusCode ?? 0
        let decoded = try? JSONDecoder().decode(AnalyzeResponse.self, from: data)

        guard status == 200, let result = decoded?.result else {
            // Log the real detail for developers; show the user a calm message.
            print("[SkinAnalysis] server \(status): \(decoded?.error ?? "no body")")
            switch status {
            case 400:       throw SkinAnalysisError.badImage
            case 401, 403:  throw SkinAnalysisError.unauthorized
            case 429:       throw SkinAnalysisError.rateLimited
            case 500...599: throw SkinAnalysisError.serverBusy
            default:        throw SkinAnalysisError.unknown
            }
        }
        return result
    }
}

private extension UIImage {
    /// Downscale so the longest edge is `maxDimension` (keeps payload + latency small).
    func cm_resized(maxDimension: CGFloat) -> UIImage {
        let longest = max(size.width, size.height)
        guard longest > maxDimension, longest > 0 else { return self }
        let scale = maxDimension / longest
        let newSize = CGSize(width: size.width * scale, height: size.height * scale)
        return UIGraphicsImageRenderer(size: newSize).image { _ in
            draw(in: CGRect(origin: .zero, size: newSize))
        }
    }
}
