//
//  SkinAnalysisService.swift
//  ClearMaxx — calls the deployed backend to analyze a face photo with Gemini.
//

import UIKit

enum CMConfig {
    /// Deployed App Engine service (project ai-backend-project-482118).
    static let backendURL = URL(string: "https://clearmaxx-dot-ai-backend-project-482118.uc.r.appspot.com")!

    /// Shared app token — matches Secret Manager `clearmaxx-app-token`.
    /// Loaded from the git-ignored `Secrets.swift` (generated by ./fetch-secrets.sh),
    /// so no token value is ever committed to the repo.
    static var appToken: String { CMSecrets.appToken }
}

// MARK: - API response models (must match backend JSON exactly)

struct SkinAnalysis: Codable {
    let clearScore: Int
    let confidence: Int
    let skinType: String
    let summary: String
    let metrics: [APIMetric]
    let routineSuggestions: [String]
}

struct APIMetric: Codable {
    let name: String
    let value: Int
    let severity: String
    let summary: String
    let ingredients: [String]
    let tips: [String]
}

private struct AnalyzeResponse: Codable {
    let success: Bool?
    let result: SkinAnalysis?
    let error: String?
}

enum SkinAnalysisError: LocalizedError {
    case encodingFailed
    case server(String)

    var errorDescription: String? {
        switch self {
        case .encodingFailed: return "Couldn't prepare the photo. Try another image."
        case .server(let m):  return m
        }
    }
}

// MARK: - Service

enum SkinAnalysisService {
    static func analyze(image: UIImage) async throws -> SkinAnalysis {
        guard let jpeg = image.cm_resized(maxDimension: 1024).jpegData(compressionQuality: 0.7) else {
            throw SkinAnalysisError.encodingFailed
        }

        var req = URLRequest(url: CMConfig.backendURL.appendingPathComponent("api/skin/analyze"))
        req.httpMethod = "POST"
        req.timeoutInterval = 60
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.setValue(CMConfig.appToken, forHTTPHeaderField: "X-App-Token")
        req.httpBody = try JSONSerialization.data(withJSONObject: ["image_base64": jpeg.base64EncodedString()])

        let (data, resp) = try await URLSession.shared.data(for: req)
        let http = resp as? HTTPURLResponse
        let decoded = try? JSONDecoder().decode(AnalyzeResponse.self, from: data)

        guard (http?.statusCode ?? 0) == 200 else {
            throw SkinAnalysisError.server(decoded?.error ?? "Server error (\(http?.statusCode ?? -1)).")
        }
        guard let result = decoded?.result else {
            throw SkinAnalysisError.server(decoded?.error ?? "Unexpected response from server.")
        }
        return result
    }
}

private extension UIImage {
    /// Downscale so the longest edge is `maxDimension` (keeps payload + latency small).
    func cm_resized(maxDimension: CGFloat) -> UIImage {
        let longest = max(size.width, size.height)
        guard longest > maxDimension, longest > 0 else { return self }
        let scale = maxDimension / longest
        let newSize = CGSize(width: size.width * scale, height: size.height * scale)
        return UIGraphicsImageRenderer(size: newSize).image { _ in
            draw(in: CGRect(origin: .zero, size: newSize))
        }
    }
}
